name: warta
version: 1.0.0+1
publish_to: none
description: Project collab untuk tugas pbo.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shimmer: 2.0.0
  flutter:
    sdk: flutter
    webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path: assets/img/warta lo.png
  ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/json/
